Unify material parameter input for phase specific quantities
MeltPoolDG/MeltPoolDG pull request #129
Opened 2021-04-13 16:08 UTC by nmuch

This PR changes the phase specific material parameter input for flow, heat, evaporation and meltpool. For all problems the capacity, conductivity, density and viscosity are imputed via the "material" section.

The material section has a `first` and `second` material. The first material is the default material for single phase problems and in two-phase problems its the material at level-set = 0. The second material is the material at level-set = 1.

I think non phase specific material quantities (e.g. surface tension coeff) can remain in the secific problem section. The absorptivity is only used by the meltpool problem, so I didn't move it to the material section.

A lot of the changed lines in the PR are the adapted .json files of the test cases. My file formatter put a lot of work into the .jsons.

2021-04-13 16:12 UTC, nmuch commented on tests/thermo_capillary_droplet.with_adaflo_support=on.mpirun=4.output
> +Newton Raphson solver converged: ||solution|| = 1.6737188613
This output file changed because the old material properties where wrong. For the flow and heat problem the two-phase parameters where flipped.

2021-04-14 07:53 UTC, mschreter requested changes
Thank you @nmuch, this was plenty of work, which is highly appreciated and will prevent us hopefully from inconsistencies in the input-files. **Please consider the formatting changes of the json-Files next time as a follow-up of such a highly delicate PR**. Reviewing was very hard and at some parts impossible (I marked the places that you can double-check them). Which formatting software did you use? Maybe we can introduce automatic formatting of json-files in our MeltPoolDG-workflow. 

I had some minor comments and also found some inconsistencies in the renaming of the parameters.

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
>        return std::make_tuple(density, capacity, conductivity);
I would prefer a call-by-reference function here 

`get_two_phase_material_parameters(VectorizedArrayType& density, VectorizedArrayType& viscosity, VectorizedArrayType& capacity, const VectorizedArrayType &ls_heaviside_val)`

Then you do not have the pack and unpack them.

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
>        return std::make_tuple(density, capacity, conductivity);
We may also think about having this function on a more central place. But this can be done in a follow-up PR.

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
>        number density      = 0.0;
We should also consider at some point a parameter `number ls_heaviside_val`. We can postpone this.

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +              adaflo_params.params.viscosity_diff =
We should make sure that one does not provide `viscosity` and `viscosity_diff` in the adaflo section. Maybe you can add an Assert
```
AssertThrow(adaflo_params.params.viscosity == 0, ExcMessage("Please specify the viscosity in the Material section."));.
```
and the same for `adaflo_params.params.viscosity_difference`.

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +              adaflo_params.params.viscosity_diff =
The same applies to `adaflo_params.params.density` and `adaflo_params.params.density_diff`.

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +              adaflo_params.params.density = material.first.density;
Is it also the convention of adaflo to have the parameter `density` for the heaviside value of level set being 0?

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +     * Default material. In case of two-phase flow; heaviside == 0
```suggestion
     * Default material. In case of two-phase flow: heaviside(level set) == 0
```

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +     * Secondary material. In case of two-phase-flow; heaviside == 1
```suggestion
     * Secondary material. In case of two-phase flow: heaviside(level set) == 1
```

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +                          "capacity of the primary material (level-set = 0)");
```suggestion
                          "capacity of the primary material (in case of two-phases corresponding to level-set = -1)");
```

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +                          "conductivity of the primary material (level-set = 0)");
```suggestion
                          "conductivity of the primary material (in case of two-phases corresponding to level-set = -1)");
```

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +                          "density of the primary material (level-set = 0)");
```suggestion
                          "density of the primary material (in case of two-phases corresponding to level-set = -1)");
```

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +                          "viscosity of the primary material (level-set = 0)");
```suggestion
                          "viscosity of the primary material (in case of two-phases corresponding to level-set = -1)");
```

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/simulations/evaporating_droplet/evaporating_droplet.json
> +    "material first density": "0.001",
Shouldn't it be 0.01?

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/simulations/recoil_pressure/recoil_pressure.json
> +    "material second density": "7743.0",
Shouldn't it be 7074.3? Please double-check the changes.

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/simulations/recoil_pressure/recoil_pressure_3d.json
> +    "material second density": "7743.0",
same here 7074.3

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/simulations/stefans_problem/stefans_problem_with_flow_amr.json
> +    "material second viscosity": "0.006"
Here must be a copy-paste error --> the parameters are entirely different than before.

2021-04-14 07:53 UTC, mschreter commented on include/meltpooldg/simulations/thermo_capillary_droplet/thermo_capillary_droplet.json
> +    "material second viscosity": "0.012"
As far as i understood liquid is level set == 1 which should be the second material. Isn't it the case?

2021-04-14 07:53 UTC, mschreter commented on tests/recoil_pressure.json
> -    "Navier-Stokes": {
Please double-check the parameters of this file. Unfortunately, due to the reformatting it is impossible to understand the changes.

2021-04-14 07:53 UTC, mschreter commented on tests/rising_bubble_ls_degree1.json
> +        "velocity degree": "2",
redundant.

2021-04-14 07:53 UTC, mschreter commented on tests/tests_not_robust/recoil_pressure_amr.json
> -    "Navier-Stokes": {
please double-check the changes of this file. Not possible to review them due to reformatting.

2021-04-14 07:53 UTC, mschreter commented on tests/tests_not_robust/recoil_pressure_fixed_solid_domain.json
> -    "Navier-Stokes": {
same here. please double check.

2021-04-14 07:53 UTC, mschreter commented on tests/thermo_capillary_droplet.json
> +    "material second viscosity": "0.012"
Same here: Shouldn't here the gas phase the first material and the liquid phase the second one?

2021-04-14 07:53 UTC, mschreter commented on tests/thermo_capillary_droplet.json
> +    "material second viscosity": "0.012"
Maybe you can add also a "visual" control, if the results are correct.

2021-04-14 07:53 UTC, mschreter commented on tests/thermo_capillary_droplet.with_adaflo_support=on.mpirun=4.output
> +Newton Raphson solver converged: ||solution|| = 1.6737188613
Okay.

2021-04-14 07:53 UTC, mschreter commented on tests/thermo_capillary_two_droplets.json
> +  "he./at": {
Typo. I am wondering why the test did not fail.

2021-04-14 13:12 UTC, nmuch reviewed
Thank you @mschreter for the great review. Sorry for that the reformatting got out of hand. I use CLion which automatically formats a file upon closing. For code it uses the `.clang-format`'s definition. I only noticed the large amount of formatting just when creating this PR.

2021-04-15 06:38 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +              adaflo_params.params.density = material.first.density;
Okay, maybe we can add a comment here that we do not have to look it up in the future again?

2021-04-15 06:40 UTC, mschreter commented on include/meltpooldg/simulations/recoil_pressure/recoil_pressure.json
> +    "material second density": "7743.0",
It could be ;-). The `json`-files in the simulations folder should serve as exemplary input files. However, the parameters in the tests folder should definitely remain the same.

2021-04-15 06:41 UTC, mschreter commented on include/meltpooldg/simulations/stefans_problem/stefans_problem_with_flow_amr.json
> +    "material second viscosity": "0.006"
Oh, that's on me :-). No that's fine, evaporation parameters have priority in this case :-).

2021-04-15 06:41 UTC, mschreter commented on include/meltpooldg/simulations/thermo_capillary_droplet/thermo_capillary_droplet.json
> +    "material second viscosity": "0.012"
Alright, thank you for clarification.

2021-04-15 06:42 UTC, mschreter commented on tests/thermo_capillary_droplet.json
> +    "material second viscosity": "0.012"
No, I think that's enough :-).

2021-04-15 07:10 UTC, mschreter commented
Hi @nmuch, I've fixed the minor missing points (add comment for adaflo and assert if adaflo density/viscosity is not equal to 1 -- it is at least better than nothing :-)). In addition, @peterrum  suggested to use a python script for formatting json files, which can be found under scripts/format_json.py. He will also add it to the indentation check of CI. It is called as follows:

```
python scripts/format_json.py myjson.json myjson.json
```
or to format all files
```
for i in $(find . -type f \( -name "*.json" \) ); do python scripts/format_json.py $i $i; done
```
Maybe you can integrate this into your workflow. Thanks a lot for your work. As soon as CI is happy, I will merge this PR.

2021-04-15 07:13 UTC, mschreter approved these changes

2021-04-15 10:47 UTC, merged