Add solidifacation to heat equation
MeltPoolDG/MeltPoolDG pull request #141
Opened 2021-05-04 09:19 UTC by nmuch

Modify heat equation to handle temperature dependent parameters.

Introduce a solidus and liquidus temperature and solid material parameters.

Linear interpolate the materal parameters in the mushy zone.

Add solidification slab case and test.

This PR does not include latent heat effects. I'll make a follow-up PR for the apparent capacity method.

2021-05-04 12:03 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +              temperature_vals.evaluate(true, true);
For reading the velocity and level-set, we might want to use `read_dof_values_plain()` instead of `gather_evaluate()` because we use the plain values (constrained or not). Here, reading the temperature using `gather_evaulate()` would lead to unphysical behaviour if there were constrains. I guess we will run into similar problems if the velocity or level-set fields are constrained. Or am I mistaken?

2021-05-04 14:49 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +              temperature_vals.evaluate(true, true);
Nevermind, the issue I had was not related to `gather_evaluate()`. It should work fine here.

2021-05-04 15:14 UTC, nmuch commented
@mschreter as discussed I changed the solidification method to use the material.second properties for the liquid's properties, so we can rename the material phase structs accordingly in a follow-up: second -> liquid, first -> gas

2021-05-04 15:50 UTC, mschreter reviewed
I'll finish for now, but still have to review certain parts of the code later.

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +   *                                              |(n+1)          Ω
```suggestion
   *                  /                       d k |              \
   *              +   | ∇N_a, k^(n+1) ∇N_b + -----| T^(n+1) ∇N_b |
   *                  \                       d T |              /
   *                                              |(n+1)          Ω
```

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +   *                                              |(n+1)          Ω
I think there is a mistake in the derivative. If this change also affects the implementation, please modify it there as well.

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +   * with the convection coefficient alpha.
```suggestion
   * with the convection coefficient denoted as α.
```

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +        !data.solidification || (material.solid.conductivity > 0.0 && material.solid.density > 0.0),
Would it be more precise to have 
```suggestion
        data.solidification && (material.solid.conductivity > 0.0 && material.solid.density > 0.0),
```

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +        !data.solidification ||
same here?

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +        !data.solidification || material.liquidus_temperature > material.solidus_temperature,
same here?

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +              if (data.solidification)
What would happen if we have `level_set_as_heaviside` and `data.solidification` defined?

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                                  shape_vals.get_value(q_index);
```suggestion
                      val_grad += d_conductivity_dT * temperature_vals.get_value(q_index) *
                                  shape_vals.get_gradient(q_index);
```

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                                        shape_vals.get_value(q_index);
Same change as in previous comment.

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                  val -= (density_old * capacity_old - density * capacity) *
This does not make sense. In case of solidification you would have multiply subtracted `density * capacity * temp_vals_old` (see lines 892-895).

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +     * solidification/melting. In the mushy zone (between solidus and liquidus temperautre) the
```suggestion
     * solidification/melting. In the mushy zone (between solidus and liquidus temperature) the
```

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +     * materal.second.<..>
```suggestion
     * material.second.<..>
```

2021-05-04 15:50 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +      const auto unbound_mushy_zone_solid_fraction =
```suggestion
/*
* Compute the solid fraction for a temperature between the liquidus and the solidus temperature. If the temperature is equal to the liquidus temperature, then the solid fraction is zero.  If the temperature is equal to the solidus temperature, then the solid fraction is one. 
*/
      const auto unbound_mushy_zone_solid_fraction =
```

2021-05-04 18:32 UTC, mschreter requested changes
Thank you @nmuch, I went through the PR and made some comments. If some of them are unclear, feel free to reach out any time.

2021-05-04 18:32 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +      const auto solid_fraction = compare_and_apply_mask<SIMDComparison::less_than>(
Couldn't you simply cut all `unbound_mushy_zone_solid_fraction` larger than 1 by 1 and smaller than 0 by 0?

2021-05-04 18:32 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                                    temperature, material.solidus_temperature, 1.0, 0.0);
Could you consider a utility function in `utilityfunctions.hpp` for that?
```cpp
template <typename number>
    VectorizedArray<number>
    limit_to_bounds(const VectorizedArray<number> &in, const number& lower_limit, const number& upper_limit)
    {
      return compare_and_apply_mask<SIMDComparison::less_than> 
               (compare_and_apply_mask<SIMDComparison::greater_than>(in,
                                                                                                    upper_limit,
                                                                                                    upper_limit,
                                                                                                     in), 
                                    lower_limit, 
                                    lower_limit, 
                                    in);
    }
```
Then you could calculate the solid_fraction as follows:
```cpp
const auto solid_fraction =  (material.liquidus_temperature - limit_to_bounds(temperature,material.solidus_temperature, material.liquidus_temperature) /
        (material.liquidus_temperature - material.solidus_temperature);
```

2021-05-04 18:32 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +    get_material_parameters_with_solidification(VectorizedArrayType &      capacity,
Since you always call `get_material_parameters` by `get_material_parameters_derivatives` would it make sense to have only one function, delivering both -- parameters and derivatives?
```suggestion
    get_solidifying_material_parameters_and_derivatives(VectorizedArrayType &      capacity,
     VectorizedArrayType &      conductivity,
     VectorizedArrayType &      density,
      VectorizedArrayType &      d_capacity_dT,
      VectorizedArrayType &      d_conductivity_dT,
      VectorizedArrayType &      d_density_dT,
      const VectorizedArrayType &temperature) const
```

2021-05-04 18:32 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +                          "Set this parameter to consider solidification.");
```suggestion
                          "Set this parameter to true to consider solidification.");
```

2021-05-04 18:32 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                        temperature, material.solidus_temperature, 1.0, 0.0) *
This coefficient is for all derivatives the same. Thus you could calculate it only once. Further, it could be nice to have a utility function for this purpose:
```cpp
template <typename number>
    VectorizedArray<bool>
    is_between(const VectorizedArray<number> &in, const number& lower_limit, const number& upper_limit)
    { ... }
```

2021-05-04 18:32 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +                          "capacity of the solid");
```suggestion
                          "capacity of the solid phase");
```

2021-05-04 18:32 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +                          "conductivity of the solid");
```suggestion
                          "conductivity of the solid phase");
```

2021-05-04 18:32 UTC, mschreter commented on include/meltpooldg/interface/parameters.hpp
> +        prm.add_parameter("material solid density", material.solid.density, "density of the solid");
```suggestion
        prm.add_parameter("material solid density", material.solid.density, "density of the solid phase");
```

2021-05-05 06:37 UTC, peterrum reviewed
@nmuch I left some small comments.

Generally, I would suggest to create in a follow-up PR a free function that contains the body of the cell loop. Currently, we have more or less 3 versions of the same code, which was only an intermediate step to get the preconditioners running.

2021-05-05 06:37 UTC, peterrum commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +      FECellIntegrator<dim, 1, number>   shape_vals(matrix_free, temp_dof_idx, this->quad_idx);
Is there a particular reason for the renaming? If no, I would like to keep the old name, since the `FEEvaluation` object is linked to the ansatz/test functions of the temperature field.

2021-05-05 06:37 UTC, peterrum commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +      VectorizedArrayType d_density_dT      = 0.0;
These can be moved into the cell loop.

2021-05-05 06:37 UTC, peterrum commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                }
To me it looks like that `temperature_vals` is now responsible for the linearlization point of the Newton solver. Let's rename this `temp_old_vals` and `shape_vals` to `temp_vals`.

2021-05-05 06:37 UTC, peterrum commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +} // namespace MeltPoolDG::Heat
Could you add a new line.

2021-05-05 08:00 UTC, mschreter commented
> @nmuch I left some small comments.
> 
> Generally, I would suggest to create in a follow-up PR a free function that contains the body of the cell loop. Currently, we have more or less 3 versions of the same code, which was only an intermediate step to get the preconditioners running.

That's a good idea. What signature of this free function do you have in mind?

2021-05-05 08:31 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +   *                                              |(n+1)          Ω
No, the derivative I wrote is correct, at least that's what our other software uses. 
First I used your variant, but Newton will not converge. I'm still not quite sure why it doesn't.

2021-05-05 08:31 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +        !data.solidification || (material.solid.conductivity > 0.0 && material.solid.density > 0.0),
For the case we don't have solidification we don't need the materal.solid parameters. Your assert would throw every time we don't have solidification enabled. We would need a both or nothing bool operator.

2021-05-05 08:31 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +        !data.solidification ||
yes

2021-05-05 08:31 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +        !data.solidification || material.liquidus_temperature > material.solidus_temperature,
yes

2021-05-05 08:31 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +              if (data.solidification)
That case does not work yet. I'll look into a method to determine the material parameters for the combined case in a follow-up. Do you want me to add an assert for now?

2021-05-05 08:31 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                                  shape_vals.get_value(q_index);
So comment above. This should work fine.

2021-05-05 08:32 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                  val -= (density_old * capacity_old - density * capacity) *
Yes. I did not change the default implementation for no solidification because the old material parameters are not set there. This tern subtracts `-density*capacity*temp_vals_old` again and add the correct `-density_old*capacity_old*temp_vals_old`. 

Maybe we should always compute the old material parameters, also if they don't change, so we don't have this weird line correcting the default equation. wdyt?

2021-05-05 08:32 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +      const auto solid_fraction = compare_and_apply_mask<SIMDComparison::less_than>(
That's what I doing here. Is there a more efficient way I not aware or? I'm curious.

2021-05-05 08:32 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                                    temperature, material.solidus_temperature, 1.0, 0.0);
Ah that's for the comment above, right?

2021-05-05 08:33 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +    get_material_parameters_with_solidification(VectorizedArrayType &      capacity,
I only call both for the tangent functions. For the residual we don't need the derivatives.

2021-05-05 08:33 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +      FECellIntegrator<dim, 1, number>   shape_vals(matrix_free, temp_dof_idx, this->quad_idx);
I renamed this to not confuse it with `temperature_vals` with holds the actual temperature values in the tangent loops. I'm aware that `shape_vals` isn't correct here. I talked to @mschreter for a better name, but we didn't find one yet. 

The problem is that we need the total temperature values in the tangent loop to determine the material parameters, but `temp_vals` does not provide those as the name suggests.

2021-05-05 08:33 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +      VectorizedArrayType d_density_dT      = 0.0;
Now I get conflicting info 🤔 @mschreter preferred them to be outside the cell loop in a previous PR.

2021-05-05 08:34 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                }
I would not name is `temp_old_vals` because then i can be confused with the `temperature_old` values or the previous time step. It's the temperature values of the current time step but the previous iteration.

2021-05-05 08:34 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +} // namespace MeltPoolDG::Heat
sure

2021-05-05 08:34 UTC, nmuch commented
Thank you @mschreter and @peterrum for your reviews. I'll implement the obvious changes right away.

> Generally, I would suggest to create in a follow-up PR a free function that contains the body of the cell loop.

Yes, that a good idea. In this PR I just implemented the new terms in the existing code. Having there sets of the same equation was quite annoying but restructuring the code is not the scope of this PR.

2021-05-05 08:39 UTC, peterrum commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                }
Since it is the linearization point, we could call it `temp_lin_vals`.

2021-05-05 08:40 UTC, peterrum commented
> That's a good idea. What signature of this free function do you have in mind?

Nothing spectacular. Since the functions will not have some local variables in the scope like the FEEval instances these need to pass explicitly. I would make the following to a function:

https://github.com/MeltPoolDG/MeltPoolDG/blob/d05eb240de4b98f833f947855510003faf4d8024/include/meltpooldg/heat/heat_transfer_operator.hpp#L418-L428

and this one to a function:

https://github.com/MeltPoolDG/MeltPoolDG/blob/d05eb240de4b98f833f947855510003faf4d8024/include/meltpooldg/heat/heat_transfer_operator.hpp#L432-L456

in particular, I would make 

https://github.com/MeltPoolDG/MeltPoolDG/blob/d05eb240de4b98f833f947855510003faf4d8024/include/meltpooldg/heat/heat_transfer_operator.hpp#L402-L404

part of the latter function.

2021-05-05 09:53 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +    get_material_parameters_with_solidification(VectorizedArrayType &      capacity,
Okay, then please ignore my previous comment :-).

2021-05-05 09:53 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                                    temperature, material.solidus_temperature, 1.0, 0.0);
Exactöy-

2021-05-05 10:01 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                  val -= (density_old * capacity_old - density * capacity) *
I agree to the last point. The "old" parameters could be modified solely in case of solidification. Maybe you can also add a todo here that in case of two-phase-flow the "old" parameters would also change depending on the old level set values...

2021-05-05 10:01 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +                                    temperature, material.solidus_temperature, 1.0, 0.0);
So please ignore the previous one :-)

2021-05-05 10:02 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +              if (data.solidification)
Yes, please add an assert so we know what to do in the future.

2021-05-05 10:04 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +        !data.solidification || (material.solid.conductivity > 0.0 && material.solid.density > 0.0),
Oh yes, I got it. Thank you for the explanation :-).

2021-05-05 10:06 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +      VectorizedArrayType d_density_dT      = 0.0;
If its about "thread-safety" then we should include them inside the loop (which is necessary in view of introducing a free function for the cell operation anyhow). Sorry for the re-correction :-).

2021-05-05 10:25 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +   *                                              |(n+1)          Ω
In my comments T^(n+1) are actually the nodal values (It would have been better to call them q_T^(n+1)). So to get the derivative one has to simply differentiate the shape functions and multiply by the nodal values, so I would prefer to modify the comment to 
```cpp
   *                  /                       d k |              \
   *              +   | ∇N_a, k^(n+1) ∇N_b + -----| T^(n+1) ∇N_b |
   *                  \                       d T |              /
   *                                              |(n+1)          Ω
   * ```
 The implementation is fine, since temperature_vales.get_gradient(q_index) corresponds to `T^(n+1) ∇N_b` and the multiplication with `shape_vals.get_value(q)` represents the multiplication with the Newton correction in the ith iteration dT^(i,n+1).

2021-05-05 11:17 UTC, mschreter commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +      VectorizedArrayType d_density_dT      = 0.0;
@nmuch: If you agree I could implement the cell operation in a free function in a follow-up PR.

2021-05-05 11:29 UTC, nmuch commented on include/meltpooldg/heat/heat_transfer_operator.hpp
> +      VectorizedArrayType d_density_dT      = 0.0;
Sure, I'll make a PR with the tangent cell loop and move the declaration of the material variables in that PR.

2021-05-05 14:28 UTC, mschreter commented
I'll merge once CI is happy.

2021-05-05 16:10 UTC, mschreter approved these changes

2021-05-05 16:10 UTC, merged