New testcase: Slotted disc
MeltPoolDG/MeltPoolDG pull request #38
Opened 2020-11-02 18:41 UTC by JPmoep

Hopefully, this pull request is working fine.

2020-11-02 18:46 UTC, peterrum reviewed
Looks good to me. @JPmoep, could you format the code (.hpp files)? For that you need to install clang-format 10 on you computer.

2020-11-02 18:54 UTC, JPmoep commented
what kind of format does this package create?

2020-11-02 20:15 UTC, mschreter commented
Thank you @JPmoep, overall it looks convincing to me :). Maybe you may have a look on my minor comments and then I will be ready to merge asap.

2020-11-03 07:52 UTC, mschreter requested changes

2020-11-04 15:26 UTC, mschreter approved these changes

2020-11-04 15:34 UTC, merged